export const movies = [
  {
    popularity: 229.296,
    vote_count: 0,
    video: false,
    poster_path: "/mWOkjqqzWiaFC65i2nFuMzM9jne.jpg",
    id: 668203,
    adult: false,
    backdrop_path: "/wuJpiGNGv7wLg52ONizLrOugYp9.jpg",
    original_language: "en",
    original_title: "Scary Movie 6",
    genre_ids: [35, 27, 53],
    title: "Scary Movie 6",
    vote_average: 0,
    overview:
      "[RUMORED]  The sixth and final installment of the Scary Movie franchise that ignores the fifth film. A parody of Scream 4 and various other horror movies, sequels and reboots that were released between the late 2010's and 2020. Takes place 15 years after the fourth film.",
    release_date: "2021-04-02"
  },
  {
    popularity: 172.29,
    id: 443791,
    video: false,
    vote_count: 893,
    vote_average: 6.4,
    title: "Underwater",
    release_date: "2020-01-08",
    original_language: "en",
    original_title: "Underwater",
    genre_ids: [27, 878, 28, 53],
    backdrop_path: "/ww7eC3BqSbFsyE5H5qMde8WkxJ2.jpg",
    adult: false,
    overview:
      "After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.",
    poster_path: "/gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg"
  },
  {
    popularity: 163.394,
    vote_count: 415,
    video: false,
    poster_path: "/worCHasSOCQD4lvlQsBcBqRwghd.jpg",
    id: 11026,
    adult: false,
    backdrop_path: "/hz4Tzv4jac2usrCpMUGJp4akkoK.jpg",
    original_language: "en",
    original_title: "Exorcist: The Beginning",
    genre_ids: [27, 9648, 53],
    title: "Exorcist: The Beginning",
    vote_average: 5.2,
    overview:
      "Having lived through traumatizing events during WWII, Father Lankester Merrin takes a sabbatical from the Church to conduct archaeological excavations in British-administered East Africa. Merrin unearths an ancient Byzantine church believed have been built and then immediately buried to keep down evil from the crypt below. The natives are convinced that uncovering the church has unleashed a demon, and begin to violently clash with the British military troops. As the village rapidly disintegrates into chaos and war, Merrin must face-off with the demon which has taken possession of somebody close to him.",
    release_date: "2004-08-20"
  },
  {
    popularity: 84.185,
    vote_count: 421,
    video: false,
    poster_path: "/rbrvkNWDyF1NKzvAlIHepFBSBJq.jpg",
    id: 539537,
    adult: false,
    backdrop_path: "/x80ZIVGUJ6plcUBcgVZ6DPKT7vc.jpg",
    original_language: "en",
    original_title: "Fantasy Island",
    genre_ids: [14, 27, 878],
    title: "Fantasy Island",
    vote_average: 5.8,
    overview:
      "A group of contest winners arrive at an island hotel to live out their dreams, only to find themselves trapped in nightmare scenarios.",
    release_date: "2020-02-12"
  },
  {
    popularity: 69.976,
    vote_count: 1592,
    video: false,
    poster_path: "/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg",
    id: 570670,
    adult: false,
    backdrop_path: "/uZMZyvarQuXLRqf3xdpdMqzdtjb.jpg",
    original_language: "en",
    original_title: "The Invisible Man",
    genre_ids: [27, 878, 53],
    title: "The Invisible Man",
    vote_average: 7.2,
    overview:
      "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
    release_date: "2020-02-26"
  },
  {
    popularity: 64.681,
    vote_count: 282,
    video: false,
    poster_path: "/mBBBXseq4k4dI63k06XIrsc02j8.jpg",
    id: 542224,
    adult: false,
    backdrop_path: "/jEPEVO48hKQB0EUNFQOSv6qtKNW.jpg",
    original_language: "en",
    original_title: "Gretel & Hansel",
    genre_ids: [14, 27, 53],
    title: "Gretel & Hansel",
    vote_average: 6.4,
    overview:
      "A long time ago in a distant fairy tale countryside, a young girl leads her little brother into a dark wood in desperate search of food and work, only to stumble upon a nexus of terrifying evil.",
    release_date: "2020-01-30"
  },
  {
    popularity: 51.802,
    vote_count: 549,
    video: false,
    poster_path: "/rmflsMjk4lxx2foNUtd1OKWv6vB.jpg",
    id: 514847,
    adult: false,
    backdrop_path: "/qfQ78ZKiouoM2yhAnfNblp9ijQE.jpg",
    original_language: "en",
    original_title: "The Hunt",
    genre_ids: [28, 27, 53],
    title: "The Hunt",
    vote_average: 6.8,
    overview:
      "Twelve strangers wake up in a clearing. They don't know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers.",
    release_date: "2020-03-11"
  },
  {
    popularity: 50.702,
    vote_count: 66,
    video: false,
    poster_path: "/dCxHXKGAadOWslqIgzEqC6P6lVU.jpg",
    id: 48266,
    adult: false,
    backdrop_path: "/19YSsPjBoMfw5Pq7oxYvXIBOz5H.jpg",
    original_language: "fr",
    original_title: "Ma mère",
    genre_ids: [18, 27],
    title: "My Mother",
    vote_average: 4.7,
    overview:
      "Based on George Bataille's posthumous and controversial novel: When his father dies, a young man is introduced by his attractive, amoral mother to a world of hedonism and depravity.",
    release_date: "2004-05-19"
  },
  {
    popularity: 45.648,
    vote_count: 161,
    video: false,
    poster_path: "/DpFMAjyE6EmIknSduykVc1pB1J.jpg",
    id: 639798,
    adult: false,
    backdrop_path: "/59b4PaPaI52LJJRNRtG3ALyUvJU.jpg",
    original_language: "es",
    original_title: "Malasaña 32",
    genre_ids: [27],
    title: "32 Malasana Street",
    vote_average: 6.4,
    overview:
      "Inspired by real events, the story centers around a family in the 70s who settles in the Madrid neighborhood of Malasaña where their new house will become the worst of their nightmares.",
    release_date: "2020-01-17"
  },
  {
    popularity: 45.549,
    vote_count: 201,
    video: false,
    poster_path: "/ff00BtvdnSHO8qoblBhiXmJKvCm.jpg",
    id: 23966,
    adult: false,
    backdrop_path: "/cG4OFBOr6ZYdXYwC5CC9l1nwxkt.jpg",
    original_language: "en",
    original_title: "Deadgirl",
    genre_ids: [27, 53, 10749],
    title: "Deadgirl",
    vote_average: 5.4,
    overview:
      "When high school misfits Rickie and JT decide to ditch school and find themselves lost in the crumbling facility of a nearby abandoned hospital, they come face-to-face with a gruesome discovery: a body of a woman stripped naked, chained to a table and covered in plastic and soon realize she is anything but dead. Quickly the boys find themselves embarking on a twisted yet poignant journey testing the limits of their friendship, and forces both to decide just how far they're willing to stretch their understanding of right and wrong.",
    release_date: "2008-09-06"
  },
  {
    popularity: 42.51,
    vote_count: 19,
    video: false,
    poster_path: "/20de4Rcmy4B0L5zyOc3Nc5F7c0D.jpg",
    id: 412546,
    adult: false,
    backdrop_path: "/uOeVTQFgr2NfEg4gK3AeUH8F9fl.jpg",
    original_language: "en",
    original_title: "Antrum",
    genre_ids: [27],
    title: "Antrum",
    vote_average: 7.2,
    overview:
      "Rumored to have been lost, Antrum appears as a cursed film from the 1970s. Viewers are warned to proceed with caution. It’s said to be a story about a young boy and girl who enter the forest in an attempt to save the soul of their recently deceased pet. They journey to “The Antrum,” they very spot the devil landed after being cast out of heaven. There, the children begin to dig a hole to hell.",
    release_date: "2018-10-14"
  },
  {
    popularity: 41.064,
    vote_count: 1539,
    video: false,
    poster_path: "/p69QzIBbN06aTYqRRiCOY1emNBh.jpg",
    id: 501170,
    adult: false,
    backdrop_path: "/A1lvRqwbLz0PIs5QyivFVzCarc6.jpg",
    original_language: "en",
    original_title: "Doctor Sleep",
    genre_ids: [18, 14, 27, 53],
    title: "Doctor Sleep",
    vote_average: 7.1,
    overview:
      "Still irrevocably scarred by the trauma he endured as a child at the Overlook, Dan Torrance has fought to find some semblance of peace. But that peace is shattered when he encounters Abra, a courageous teenager with her own powerful extrasensory gift, known as the 'shine'. Instinctively recognising that Dan shares her power, Abra has sought him out, desperate for his help against the merciless Rose the Hat and her followers.",
    release_date: "2019-10-30"
  },
  {
    popularity: 38.196,
    vote_count: 2127,
    video: false,
    poster_path: "/pIcV8XXIIvJCbtPoxF9qHMKdRr2.jpg",
    id: 338967,
    adult: false,
    backdrop_path: "/3ghImmHdp4RnC3UkL6hpLayclnb.jpg",
    original_language: "en",
    original_title: "Zombieland: Double Tap",
    genre_ids: [28, 35, 27],
    title: "Zombieland: Double Tap",
    vote_average: 7,
    overview:
      "Columbus, Tallahassee, Wichita, and Little Rock move to the American heartland as they face off against evolved zombies, fellow survivors, and the growing pains of the snarky makeshift family.",
    release_date: "2019-10-09"
  },
  {
    popularity: 37.567,
    vote_count: 3806,
    video: false,
    poster_path: "/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
    id: 474350,
    adult: false,
    backdrop_path: "/8moTOzunF7p40oR5XhlDvJckOSW.jpg",
    original_language: "en",
    original_title: "It Chapter Two",
    genre_ids: [18, 14, 27],
    title: "It Chapter Two",
    vote_average: 6.8,
    overview:
      "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
    release_date: "2019-09-04"
  },
  {
    popularity: 36.234,
    vote_count: 7857,
    video: false,
    poster_path: "/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    id: 447332,
    adult: false,
    backdrop_path: "/roYyPiQDQKmIKUEhO912693tSja.jpg",
    original_language: "en",
    original_title: "A Quiet Place",
    genre_ids: [18, 27, 878],
    title: "A Quiet Place",
    vote_average: 7.3,
    overview:
      "A family is forced to live in silence while hiding from creatures that hunt by sound.",
    release_date: "2018-04-03"
  },
  {
    popularity: 34.734,
    vote_count: 12169,
    video: false,
    poster_path: "/lli31lYTFpvxVBeFHWoe5PMfW5s.jpg",
    id: 381288,
    adult: false,
    backdrop_path: "/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg",
    original_language: "en",
    original_title: "Split",
    genre_ids: [27, 53],
    title: "Split",
    vote_average: 7.3,
    overview:
      "Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.",
    release_date: "2016-09-26"
  },
  {
    popularity: 34.281,
    vote_count: 199,
    video: false,
    poster_path: "/vkwgzCBBiY3C1XEy0WakYfMOvnG.jpg",
    id: 548473,
    adult: false,
    backdrop_path: "/iyn2JQsftaqhQlXYaCCvn8udM5i.jpg",
    original_language: "en",
    original_title: "Color Out of Space",
    genre_ids: [27, 878],
    title: "Color Out of Space",
    vote_average: 6.2,
    overview:
      "The Gardner family moves to a remote farmstead in rural New England to escape the hustle of the 21st century. They are busy adapting to their new life when a meteorite crashes into their front yard, melts into the earth, and infects both the land and the properties of space-time with a strange, otherworldly colour. To their horror, the family discovers this alien force is gradually mutating every life form that it touches—including them.",
    release_date: "2020-01-24"
  },
  {
    popularity: 33.749,
    vote_count: 212,
    video: false,
    poster_path: "/uiMHiHp9eAjJty8rddoUnL9G5fU.jpg",
    id: 492611,
    adult: false,
    backdrop_path: "/lYJDf7oa1r9JvRITN1M2Lzis01D.jpg",
    original_language: "en",
    original_title: "The Turning",
    genre_ids: [27, 53],
    title: "The Turning",
    vote_average: 5.9,
    overview:
      "A young woman quits her teaching job to be a private tutor (governess) for a wealthy young heiress who witnessed her parent's tragic death. Shortly after arriving, the girl's degenerate brother is sent home from his boarding school. The tutor has some strange, unexplainable experiences in the house and begins to suspect there is more to their story.",
    release_date: "2020-01-23"
  },
  {
    popularity: 33.672,
    vote_count: 10686,
    video: false,
    poster_path: "/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg",
    id: 694,
    adult: false,
    backdrop_path: "/AdKA2F1SzYPhSZdEbjH1Zh75UVQ.jpg",
    original_language: "en",
    original_title: "The Shining",
    genre_ids: [27, 53],
    title: "The Shining",
    vote_average: 8.2,
    overview:
      "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
    release_date: "1980-05-23"
  },
  {
    popularity: 32.927,
    vote_count: 8876,
    video: false,
    poster_path: "/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    id: 348,
    adult: false,
    backdrop_path: "/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg",
    original_language: "en",
    original_title: "Alien",
    genre_ids: [27, 878],
    title: "Alien",
    vote_average: 8.1,
    overview:
      "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
    release_date: "1979-05-25"
  }
];

export default movies;
